nome = str(input('\033[30;1minsira seu nome completo:')).strip()
primeiro = nome.split()
ultimo = nome.split()
print('prazer em te conhecer')
print('seu primeiro nome é \033[34m{}\033[30m'.format(primeiro[0]))
print('e seu último nome é \033[34m{}\033[m'.format(ultimo[-1]))
